# Site settings
title: molsson's blog
email: martin@minimum.se
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mo.github.io" # the base hostname & protocol for your site
twitter_username: mo_molsson
github_username: mo
linkedin_username: hansmartinolsson

# Other
exclude:
  - 'gulpfile.js'

# Build settings
markdown: kramdown
